#! /bin/sh

# Setup monitors
~/.config/monitors.sh

# Launch sxhkd
sxhkd &

# Desktops
bspc monitor DP-3 -d 1 2 3
bspc monitor DP-2 -d 4 5 6
bspc monitor HDMI-1 -d 7 8 9

# Launch polybar
~/.config/polybar/launch.sh &

# Border and Gap
bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 25

# Configuration
bspc config split_ratio 0.50

# Mouse
bspc config focus_follows_pointer true

# Monocle mode settings
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle true

# Colors
bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"

# Rules
bspc rule -a Brave_browser desktop='4' follow=on
bspc rule -a signal desktop='2'
bspc rule -a obsidian desktop='1'
bspc rule -a copyq state=floating sticky
bspc rule -a Thunar state=floating

# Auto-start
picom --config "$HOME/.config/bspwm/picom.conf" &
